print('hello')
print('whats your name')
myname = input()
print('its good to meet you', myname)
print('the length of the name is')
print(len(myname))
print('whats your age')
myage = input()
print('you will be '+str(int(myage)+1)+' in a year')
